#!/bin/sh

wget -nc http://download.jetbrains.com/idea/ideaIC-13.1.1.tar.gz -O /tmp/idea-13.1.tar.gz
tar -xzf /tmp/idea-13.1.tar.gz -C /opt
rm -f /usr/bin/idea
ln -s /opt/idea-IC-135.480/bin/idea.sh /usr/bin/idea

