#!/bin/sh

CHROME_VERSION=33
CHROME_DEB=/tmp/chrome-${CHROME_VERSION}.deb

# Install Google Chrome
if [ ! -f ${CHROME_DEB} ]; then
    wget -nc https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O ${CHROME_DEB}
	dpkg -i ${CHROME_DEB}
fi
